apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kt-ingress-grpc
  annotations:
    nginx.org/grpc-services: "grpc.reflection.v1alpha,google.keytransparency.v1"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "localhost"
    - "127.0.0.1"
    secretName: kt-tls
  rules:
    - host: localhost
      http:
       paths:
       - path: /grpc.reflection.v1alpha
         backend:
           serviceName: server
           servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kt-ingress-http
spec:
  tls:
  - hosts:
    - "localhost"
    - "127.0.0.1"
    secretName: kt-tls
  rules:
    - host: localhost
      http:
       paths:
       - path: /
         backend:
           serviceName: server
           servicePort: 8080
