commonLabels:
  app.kubernetes.io/name: keytransparency

resources:
- configmap.yaml
- ingress.yaml
- init-pod.yaml
- log-server-deployment.yaml
- log-server-service.yaml
- log-signer-deployment.yaml
- log-signer-service.yaml
- map-server-deployment.yaml
- map-server-service.yaml
- monitor-deployment.yaml
- monitor-service.yaml
- prometheus-deployment.yaml
- prometheus-configmap.yaml
- prometheus-service.yaml
- prometheus-rbac.yaml
- sequencer-deployment.yaml
- sequencer-service.yaml
- server-deployment.yaml
- server-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/key-transparency/init
  newTag: 15d6d36653d9cce064d2b94ee8d55cab0127fa8b
- name: gcr.io/key-transparency/keytransparency-monitor
  newTag: 15d6d36653d9cce064d2b94ee8d55cab0127fa8b
- name: gcr.io/key-transparency/keytransparency-sequencer
  newTag: 15d6d36653d9cce064d2b94ee8d55cab0127fa8b
- name: gcr.io/key-transparency/keytransparency-server
  newTag: 15d6d36653d9cce064d2b94ee8d55cab0127fa8b
- name: gcr.io/trillian-opensource-ci/log_server
  newTag: v1.3.10
- name: gcr.io/trillian-opensource-ci/log_signer
  newTag: v1.3.10
- name: gcr.io/trillian-opensource-ci/map_server
  newTag: v1.3.10
