apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: log-server
  name: log-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: log-server
    spec:
      containers:
      - name: trillian-logserver
        args: [
        "--mysql_uri=test:zaphod@tcp(db:3306)/test",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--alsologtostderr"
        ]
        image: gcr.io/trillian-opensource-ci/log_server:latest
        livenessProbe:
         httpGet:
           path: /metrics
           port: 8091
        name: log-server
        ports:
        - containerPort: 8090
        - containerPort: 8091
        resources: {}
      restartPolicy: Always
status: {}
