apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8081'
    prometheus.io/scheme: 'http'
  labels:
    io.kompose.service: sequencer
  name: sequencer
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: sequencer
status:
  loadBalancer: {}
