apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8081'
    prometheus.io/scheme: 'http'
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
  - name: "grpc-api"
    port: 443
    targetPort: 8080
    nodePort: 30080
  - name: "http-metrics"
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    io.kompose.service: server
  type: NodePort # Required for ingress
status:
  loadBalancer: {}
