apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
  - name: "grpc-api"
    port: 443
    targetPort: 8080
  - name: "http-metrics"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: server
  type: NodePort
status:
  loadBalancer: {}
