version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - gdbelvin
  ignore:
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: cloud.google.com/go/spanner
    versions:
    - 1.13.0
    - 1.14.1
    - 1.15.0
    - 1.16.0
  - dependency-name: github.com/prometheus/client_golang
    versions:
    - 1.9.0
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
  - dependency-name: github.com/grpc-ecosystem/go-grpc-middleware
    versions:
    - 1.2.2
