run:
  skip-file:
    - ".+\\.pb\\.go"
    - ".+\\.pb\\.gw\\.go"

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.2
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - scopelint
    - gochecknoinits
    - gochecknoglobals
    - lll
    - interfacer

issues:
  exclude:
    - .((os\.)?std(out|err)\..*|.*Close|.*Flush|.*Write|.*Serve|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv).
