ct-key: "../certificate-transparency/test/testdata/ct-server-key-public.pem"
ct-url: "http://107.178.246.112"
vrf:    "keys/test_verification_keys/vrf-pubkey.pem"
kt-key: "keys/test_verification_keys/server.crt"
kt-sig: "keys/test_verification_keys/p256-pubkey.pem"
domain: "example.com"
kt-url: "localhost:5003"
client-secret: "client_secret.json"
