language: go
go:
- 1.x
dist: bionic

go_import_path: github.com/google/keytransparency

services:
- docker
cache:
  directories:
  - "$HOME/gcloud/"
  - "$HOME/gopath/pkg/mod"
env:
  global:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GO111MODULE=on

before_install:
  - |
    if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
        mkdir -p $HOME/gcloud
        wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud
        cd $HOME/gcloud
        tar xzf google-cloud-sdk.tar.gz;
        ./google-cloud-sdk/install.sh -q;
        cd $TRAVIS_BUILD_DIR
    fi
  - source "$HOME/gcloud/google-cloud-sdk/path.bash.inc"
  - gcloud -q components update
  - gcloud -q version
  - wget --version

install:
  - gcloud -q components install kubectl
  - docker --version
  - docker-compose --version
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - if [ "$GO111MODULE" = "auto" ]; then go get -t -v ./... ; fi

script:
  - go build ./...
  - golangci-lint run --deadline=5m
  - go test ./... -coverprofile=coverage1.txt
  - go test ./impl/integration/ -coverprofile=coverage2.txt -coverpkg=./...
  - ./scripts/integration.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - openssl aes-256-cbc -K $encrypted_555d9b2948d2_key -iv $encrypted_555d9b2948d2_iv
    -in client_secrets.json.enc -d | gcloud auth activate-service-account --key-file /dev/stdin
  - go get github.com/google/trillian/server/trillian_log_server
  - go get github.com/google/trillian/server/trillian_log_signer
  - go get github.com/google/trillian/server/trillian_map_server

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
