language: go
go:
- "1.x"
dist: trusty
services:
- docker-ce
cache:
  directories:
  - $HOME/google-cloud-sdk/
env:
  global:
  - DOCKER_COMPOSE_VERSION="1.13.0"
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GOMETALINTER_VERSION="$(.travis/get-gometalinter-version.sh)"
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin:${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

addons:
  apt:
    packages:
    - python3-pip

install:
  - ./.travis/gometalinter-install.sh
  - go get -t ./...
  
cache: 
  directories:
  - ${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

script:
  - go build ./...
  - gometalinter ./...
  - go test ./... -coverprofile=coverage1.txt
  - go test ./impl/integration/ -coverprofile=coverage2.txt -coverpkg=./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip3 install --user docker-compose
  - docker --version
  - docker-compose --version
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet components install kubectl
  - gcloud --quiet version
  - openssl aes-256-cbc -K $encrypted_a1eb99cfc21e_key -iv $encrypted_a1eb99cfc21e_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
  - tar -xzf travis_secrets.tar.gz
  - gcloud auth activate-service-account --key-file service_key.json
  - rm -f service_key.json
  - go get github.com/google/trillian/server/trillian_log_server
  - go get github.com/google/trillian/server/trillian_log_signer
  - go get github.com/google/trillian/server/trillian_map_server

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
