language: go

go:
  - 1.8

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - parallel

install:
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell
  - go get ./...

script:
  - make
  - make travis-presubmit
  - ./coverage.sh 

after_success:
  - bash <(curl -s https://codecov.io/bash)
