ignore: 
  - "**/*.pb.go"     # ignore generated protos
  - "**/*.pb.gw.go"  # ignore generated protos
coverage:
  range: 60..80
  status:
    project:
      default:
        threshold: 1 # Allow coverage to drop by 1%
    patch:
      default:
        threshold: 1 # Allow coverage to drop by 1%
