version: "3"
services:
  prometheus:
    depends_on:
      - kt-server
      - kt-signer
    build: 
      context: .
      dockerfile: prometheus/Dockerfile
    ports:
      - 9090:9090

  db:
    image: mysql
    volumes:
      - ../trillian/storage/mysql/storage.sql:/docker-entrypoint-initdb.d/storage.sql
    restart: always
    environment:
      MYSQL_PASSWORD: zaphod
      MYSQL_USER: test
      MYSQL_DATABASE: test
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  trillian-log:
    depends_on:
      - db
    image: trillian_log_server:latest
    build: 
      context: ../trillian
      dockerfile: server/trillian_log_server/Dockerfile
    restart: always
    ports:
      - "8090:8090" # RPCs
      - "8091:8091" # Metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  trillian-log-signer:
    depends_on:
      - db
    image: trillian_log_signer:latest
    volumes:
         - ../keytransparency/genfiles:/kt
    build: 
      context: ../trillian
      dockerfile: server/trillian_log_signer/Dockerfile
    restart: always
    ports:
      - "8092:8091" # Metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod
      GOOGLE_APPLICATION_CREDENTIALS: /genfiles/service_key.json
      KEY: /kt/server.key
      CERT: /kt/server.crt
      VRF_PRIV: /kt/vrf-key.pem
      VRF_PUB: /kt/vrf-pubkey.pem
      SIGN_KEY: /kt/p256-key.pem
      SIGN_KEY_PW: "towel"
      SEQUENCER_PERIOD: 2.5s # shorter than kt-signer period.

  trillian-map:
    depends_on:
      - db
    image: trillian_map_server:latest
    build: 
      context: ../trillian
      dockerfile: server/trillian_map_server/Dockerfile
    restart: always
    ports:
      - "8093:8090" # RPCs
      - "8094:8091" # Metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  kt-server:
    depends_on:
      - db
      - trillian-log
      - trillian-map
    build:
      context: .
      dockerfile: ./cmd/keytransparency-server/Dockerfile
    image: keytransparency-server:latest
    volumes:
      - ./genfiles/:/kt/
    restart: always
    ports:
      - "8080:8080" # json & grpc
      - "8081:8081" # metrics
    environment:
      LOG_ID: 4450861294505218766 # Update with trillian admin CLI.
      LOG_URL: trillian-log:8090
      MAP_ID: 5698043027494814677 # Update with trillian admin CLI.
      MAP_URL: trillian-map:8090
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod
      GOOGLE_APPLICATION_CREDENTIALS: /kt/service_key.json
      KEY: /kt/server.key
      CERT: /kt/server.crt
      VRF_PRIV: /kt/vrf-key.pem
      VRF_PUB: /kt/vrf-pubkey.pem
      TLS_KEY_PATH: /kt/server.key
      TLS_CRT_PATH: /kt/server.crt

  kt-signer:
    depends_on:
      - db
      - trillian-log
      - trillian-map
    build:
      context: .
      dockerfile: ./cmd/keytransparency-signer/Dockerfile
    image: keytransparency-signer:latest
    volumes:
      - ./genfiles/:/kt/
      - ../trillian/testdata/:/trillian/
    ports:
      - "8082:8081" # metrics
    restart: always
    environment:
      LOG_ID: 4450861294505218766 # Update with trillian admin CLI.
      LOG_URL: trillian-log:8090
      MAP_ID: 5698043027494814677 # Update with trillian admin CLI.
      MAP_URL: trillian-map:8090
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod
      GOOGLE_APPLICATION_CREDENTIALS: /kt/service_key.json
      KEY: /kt/server.key
      LOG_KEY: /trillian/log-rpc-server.pubkey.pem
      CERT: /kt/server.crt
      VRF_PRIV: /kt/genfiles/vrf-key.pem
      VRF_PUB: /kt/genfiles/vrf-pubkey.pem
      SIGN_KEY: /trillian/log-rpc-server.privkey.pem
      SIGN_KEY_PW: towel
      MIN_SIGN_PERIOD: 5s

volumes:
  kt:

