kind: ConfigMap 
apiVersion: v1 
metadata:
  name: configmap 
data:
  DB_NAME: projects/key-transparency/instances/keytransparency-dev/databases/sandbox
  DB_ENGINE: cloud_spanner
  GOOGLE_APPLICATION_CREDENTIALS: /secrets/cloudspanner/credentials.json

