bases:
- ../../base
resources:
- managed-cert.yaml
patches:
- path: cloudsql-sidecar.yaml
  target:
    kind: Deployment
- path: prometheus-sidecar.yaml
  target:
    kind: Deployment
    name: prometheus
patchesStrategicMerge:
- configmap.yaml
- ingress.yaml
- server-service.yaml
