---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    run: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    run: mysql
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - name: mysql
        image: us.gcr.io/key-transparency/db
        ports:
          - containerPort: 3306
            name: mysql
        env:
            - name: MYSQL_USER
              value: test
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_PASSWORD
              value: zaphod
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
---