apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-to-sd
  name: prometheus-to-sd
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus-to-sd
    spec:
      containers:
      - command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=logserver:http://log-server:8091/metrics
        - --source=logsigner:http://log-signer:8091/metrics
        - --source=keyserver:http://server:8081/metrics
        - --source=sequencer:https://sequencer:8080/metrics
        - --pod-id=prometheus-to-sd
        - --namespace-id=default
        - --metrics-resolution=5s
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        name: prometheus-to-sd
        ports:
        - containerPort: 6060
        resources: {}
      restartPolicy: Always
status: {}
