name: Golang CI Lint
on: [push]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
      - uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
